<?php         
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<script src='http://code.jquery.com/jquery-latest.min.js' type='text/javascript'></script>
<script>
function zub(){
$.ajax({
    // the URL for the request
    url: "",
 
    // the data to send (will be converted to a query string)
    data: {
        id: 123
    },
 
    type: "POST",
 
    dataType : "json",
 
    success: function( json ) {
        $( "#message_div" ).html(json.id);
        //$( "<h1/>" ).text( json.title ).appendTo( "body" );
        //$( "<div class=\"content\"/>").html( json.html ).appendTo( "body" );
    },
 
    // code to run if the request fails; the raw request and
    // status codes are passed to the function
    error: function( xhr, status ) {
        alert(status);
    },
 
    // code to run regardless of success or failure
    complete: function( xhr, status ) {
        alert( "The request is complete!" );
    }
});
}
</script>

<input type="textarea" id=message name=message>
<input type=button id=submit name=submit value="press" onclick="javascript:zub();">
<div id=message_div></div>

<p><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'add'));?>">Add new album</a></p>
<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escape($album->title);?></td>
    <td><?php echo $this->escape($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
